Repository kuzzleio/kuzzle-common-objects, pull requests merged in 2018-07, with the labels that each got.

#67 Add a context.connection object
  README.md
  lib/models/requestContext.js
  lib/utils/assertType.js
  package-lock.json
  package.json
  test/models/requestContext.test.js
  test/utils/assertType.test.js
Labels: changelog:enhancements

#68 Release 3.0.8
  README.md
  lib/models/requestContext.js
  lib/utils/assertType.js
  package-lock.json
  package.json
  test/models/requestContext.test.js
  test/utils/assertType.test.js
Labels: release

#69 Fix Request serialization
  .gitignore
  README.md
  lib/models/requestContext.js
  lib/models/requestInput.js
  lib/request.js
  package-lock.json
  package.json
  test/request.test.js
Labels: changelog:bug-fixes

#71 Hotfix: connection.id and connection.protocol should not be read-only
  lib/models/requestContext.js
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#70 add a deprecation jsdoc to the ParseError object
  lib/errors/parseError.js
Labels: changelog:enhancements

#72 Make console.log output Request & co
  lib/models/requestContext.js
  lib/models/requestInput.js
  lib/models/requestResponse.js
  lib/request.js
  test/models/requestResponse.test.js
Labels: changelog:enhancements

#73 Release 3.0.11
  lib/errors/parseError.js
  lib/models/requestContext.js
  lib/models/requestInput.js
  lib/models/requestResponse.js
  lib/request.js
  package-lock.json
  package.json
  test/models/requestResponse.test.js
Labels: release

#74 Release 3.0.12
  package-lock.json
  package.json
Labels: release

#75 Hotfix: RequestInput.args contains recognized properties
  lib/models/requestInput.js
  package-lock.json
  package.json
  test/models/requestInput.test.js
Labels: changelog:bug-fixes
